force-app/main/default/objects/Job_Posting__c/Job_Posting__c.object-meta.xml
<CustomObject>
    <label>Job Posting</label>
    <nameField>
        <label>Job Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Posting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Posting__c/fields/Application_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Application_Quantity__c</fullName>
    <label>Application Quantity</label>
    <summaryForeignKey>Job_Application__c.Job_Posting__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Offer Stage</fullName>
            </value>
            <value>
                <fullName>Closed - Hired</fullName>
            </value>
            <value>
                <fullName>Closed - No Hire</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/triggerHandlers/JobPostingTriggerHandler.cls
public with sharing class JobPostingTriggerHandler extends TriggerHandler {
    
    public JobPostingUtils jobPostingUtils {
        get {
            if (jobPostingUtils == null) {
                jobPostingUtils = new JobPostingUtils();
            }

            return jobPostingUtils;
        }
        set;
    }
    public override void beforeUpdate() {
        Map<Id, Job_Posting__c> oldMap = (Map<Id, Job_Posting__c>) Trigger.oldMap;
        Map<Id, Job_Posting__c> newMap = (Map<Id, Job_Posting__c>) Trigger.newMap;

        for (Job_Posting__c updatedJobPost : newMap.values()) {
            if (updatedJobPost.Application_Quantity__c != oldMap.get(updatedJobPost.Id).Application_Quantity__c 
                && ConstantUtility.STATUS_BEFORE_PROGRESS.contains(updatedJobPost.Status__c)
                && oldMap.get(updatedJobPost.Id).Application_Quantity__c == 0) {

                jobPostingUtils.updateJobPostingStatus(updatedJobPost, ConstantUtility.IN_PROGRESS_STATUS);

            }
        
        }
    }
}